version: '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "3000:3000"
    depends_on:
      - api
  mobile:
    build: ./mobile
    volumes:
      - ./mobile:/home/node/app
    ports:
      - "19000:19000"
    depends_on:
      - api
  api:
    build: ./api
    volumes:
      - ./api:/home/node/app
    ports:
      - "3001:3001"
